services:
   rules:
    build:
      context: ./rules-container/.devcontainer
      args:
        VARIANT: "11-buster"
        INSTALL_MAVEN: "true"
        INSTALL_GRADLE: "true"
        INSTALL_GRAALVM: "true"
        GRAALVM_VERSION: "22.1.0"
        NODE_VERSION: "none"
    working_dir: /workspaces
    network_mode: bridge
    entrypoint: bash
    command:
      - -c
      - |
        tail -f /dev/null
    ports:
      - 5005:5005
    volumes:
      - .:/workspaces
      - ./.m2:/home/vscode/.m2
   testing:
    build:
      context: ./rules-testing-container/.devcontainer
      args:
        VARIANT: "16-bullseye"
    working_dir: /workspaces
    network_mode: bridge
    entrypoint: bash
    command:
      - -c
      - |
        tail -f /dev/null
    volumes:
      - .:/workspaces
      - ./.node_modules:/workspaces/rules-testing-container/node_modules